version: 2.1
jobs:
  build:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
      - run: echo "this is working"

workflows:
  build:
    jobs:
      - build
